.\"             -*-Nroff-*-
.\"
.TH "o" 1 "07 Nov 2019" "" ""
.SH NAME
o \- an editor
.SH SYNOPSIS
.B o
filename [LINE NUMBER]
.sp
.SH DESCRIPTION
Edit an existing file or create a new one.
.sp
.SH OPTIONS
.sp
The line number can be prefixed with \fB+\fP, or be a suffix of the filename if prefixed with \fB:\fP.
.sp
.TP
.B \-v or\-\-version
displays the current version number
.TP
.B \-h or \-\-help
displays brief usage information
.PP
.SH KEYBINDINGS
.sp
.B ctrl-q
  Quit o.
.sp
.B ctrl-s
  Save the file.
.sp
.B ctrl-o
  Format the current file with \fBgoimport\fP or \fBclang-format\fP, depending on the file extension.
.sp
.B ctrl-a
  Go to start of ithe line, or to the start of the text if already at the start of the line, then to the previous paragraph if at the start of the line.
.sp
.B ctrl-e
  Go to end of the line, then to th next paragraph.
.sp
.B ctrl-p
  Scroll up 10 lines.
.sp
.B ctrl-n
  Scroll down 10 lines or go to the next match if a search is active.
.sp
.B ctrl-k
  Delete all characters to the end of the line. Delete the line if it is empty.
.sp
.B ctrl-g
  Toggle a status line at the bottom for displaying: filename, line, column, unicode number and word count
.sp
.B ctrl-d
  Delete a single character.
.sp
.B ctrl-t
  Toggle syntax highlighting.
.sp
.B ctrl-y
  Toggle between "text" and "draw mode" (for ASCII graphics).
.sp
.B ctrl-x
  Cut the current line.
.sp
.B ctrl-c
  Copy the current line.
.sp
.B ctrl-v
  Paste the current line.
.sp
.B ctrl-b
  Bookmark the current position.
.sp
.B ctrl-j
  Jump to the bookmark.
.sp
.B ctrl-u
  Undo (`ctrl-z` is also possible, but may background the application).
.sp
.B ctrl-l
  Jump to a specific line number.
.sp
.B ctrl-f
  Search for a string.
.sp
.B esc
  Redraw the screen and clear the last search.
.sp
.B ctrl-space
  Build the program with either `cxx` or `go build`.
.sp
.B ctrl-w
  Toggle single-line comments.
.sp
.B ctrl-r
  Render the current text to a PNG image.
.sp
.SH "WHY"
.sp
I wanted to write a simple editor that only used VT100 terminal codes.
.SH "SEE ALSO"
.BR micro (1)
.BR nano (1)
.SH BUGS
Lines longer than the terminal width are not handled gracefully.
.SH VERSION
2.10.2
.SH AUTHOR
.B o
was written by  Alexander F. Rødseth <xyproto@archlinux.org>
