Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  config.vm.box = "generic/freebsd11"
  config.vm.base_mac = "00deadbeef00"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.shell = "sh"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", path: "runtests.sh"

  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end
end
